# Generated by Django 4.1.5 on 2023-01-25 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RideOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dest_addr', models.CharField(max_length=150)),
                ('arrival', models.DateTimeField()),
                ('num_passenger', models.PositiveSmallIntegerField(default=1)),
                ('vehicle_type', models.CharField(choices=[('E', 'Economy'), ('C', 'Comfort'), ('P', 'Premium')], default='E', max_length=1)),
                ('special_request', models.CharField(blank=True, max_length=300)),
                ('sharable', models.BooleanField()),
                ('num_sharer', models.PositiveSmallIntegerField(blank=True, default=0)),
                ('status', models.CharField(default='open', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RideSharer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dest_addr', models.CharField(max_length=150)),
                ('arrival_start', models.DateTimeField()),
                ('arrival_end', models.DateTimeField()),
                ('num_passengers', models.PositiveSmallIntegerField(default=1)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.rideowner')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
        migrations.AddField(
            model_name='rideowner',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user'),
        ),
        migrations.CreateModel(
            name='RideDriver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(choices=[('E', 'Economy'), ('C', 'Comfort'), ('P', 'Premium')], max_length=1)),
                ('plate_num', models.CharField(max_length=10)),
                ('max_passengers', models.PositiveSmallIntegerField()),
                ('special_request', models.CharField(blank=True, max_length=300)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
    ]
