# Generated by Django 4.1.5 on 2023-01-28 20:47

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ridedriver',
            name='id',
        ),
        migrations.AddField(
            model_name='rideowner',
            name='driver_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='rideowner',
            name='plate_num',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='ridedriver',
            name='max_passengers',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='ridedriver',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='users.user'),
        ),
        migrations.AlterField(
            model_name='rideowner',
            name='num_passenger',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='ridesharer',
            name='num_passengers',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
