# Generated by Django 4.1.5 on 2023-01-28 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_ridedriver_id_rideowner_driver_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ridedriver',
            name='username',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='users.user'),
        ),
    ]
