# Generated by Django 4.1.5 on 2023-01-29 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_ridesharer_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='ridesharer',
            name='owner_id',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='users.rideowner'),
        ),
        migrations.AlterField(
            model_name='ridesharer',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user'),
        ),
    ]
