# Generated by Django 4.1.5 on 2023-01-29 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_ridesharer_owner_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ridesharer',
            name='owner_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.rideowner'),
        ),
    ]
