# Generated by Django 4.1.5 on 2023-01-29 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_ridesharer_owner_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ridesharer',
            name='owner_id',
        ),
        migrations.AlterField(
            model_name='ridesharer',
            name='username',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.user'),
        ),
    ]
