# Generated by Django 4.1.5 on 2023-01-29 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_ridesharer_owner_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ridesharer',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user'),
        ),
    ]
