# Generated by Django 4.1.5 on 2023-01-29 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_ridesharer_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ridesharer',
            name='owner_id',
            field=models.BigIntegerField(blank=True, default=-1),
        ),
    ]
