# Generated by Django 4.1.5 on 2023-01-29 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_ridesharer_owner_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ridesharer',
            name='owner_id',
            field=models.ForeignKey(blank=True, default=-1, on_delete=django.db.models.deletion.CASCADE, to='users.rideowner'),
        ),
    ]
