# Generated by Django 4.1.5 on 2023-01-29 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_ridesharer_owner_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default='@example.com', max_length=254),
        ),
    ]
