# Generated by Django 4.1.5 on 2023-02-02 21:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ridedriver',
            name='vehicle_type',
            field=models.CharField(choices=[('Economy', 'Economy'), ('Comfort', 'Comfort'), ('Premium', 'Premium')], max_length=15),
        ),
        migrations.AlterField(
            model_name='rideowner',
            name='arrival',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='rideowner',
            name='vehicle_type',
            field=models.CharField(choices=[('Economy', 'Economy'), ('Comfort', 'Comfort'), ('Premium', 'Premium')], default='Economy', max_length=15),
        ),
        migrations.AlterField(
            model_name='ridesharer',
            name='arrival_end',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 2, 18, 6, 13, 187684)),
        ),
        migrations.AlterField(
            model_name='ridesharer',
            name='arrival_start',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
