# Generated by Django 4.1.5 on 2023-02-03 21:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0041_alter_ridesharer_arrival_end'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ridedriver',
            name='vehicle_type',
            field=models.CharField(choices=[('Sedan', 'Sedan'), ('Coupe', 'Coupe'), ('Sports Car', 'Sports Car'), ('Hatchback', 'Hatchback'), ('Station Wagon', 'Station Wagon'), ('SUV', 'SUV')], max_length=15),
        ),
        migrations.AlterField(
            model_name='rideowner',
            name='vehicle_type',
            field=models.CharField(choices=[('Sedan', 'Sedan'), ('Coupe', 'Coupe'), ('Sports Car', 'Sports Car'), ('Hatchback', 'Hatchback'), ('Station Wagon', 'Station Wagon'), ('SUV', 'SUV')], default='Economy', max_length=15),
        ),
        migrations.AlterField(
            model_name='ridesharer',
            name='arrival_end',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 3, 18, 48, 9, 126012)),
        ),
    ]
