# Generated by Django 4.1.5 on 2023-02-06 01:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0042_alter_ridedriver_vehicle_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ridesharer',
            name='arrival_end',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 5, 22, 12, 50, 621122)),
        ),
    ]
