# Generated by Django 4.0.8 on 2023-02-14 02:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_info', models.SmallIntegerField()),
                ('vehicle_type', models.CharField(choices=[('b', 'BMW'), ('f', 'Ford'), ('k', 'Kia'), ('m', 'Maserati'), ('n', 'Nissan')], max_length=1)),
                ('maxslot', models.SmallIntegerField()),
                ('plate_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=100)),
                ('arrival_time', models.DateTimeField()),
                ('total_passanger', models.SmallIntegerField()),
                ('vehicle_type', models.CharField(choices=[('b', 'BMW'), ('f', 'Ford'), ('k', 'Kia'), ('m', 'Maserati'), ('n', 'Nissan')], max_length=1)),
                ('comfirmed_order_driver', models.SmallIntegerField(blank=True, null=True)),
                ('plate_numer', models.IntegerField(blank=True, null=True)),
                ('shareable', models.BooleanField()),
                ('shared_people', models.CharField(blank=True, max_length=100, null=True)),
                ('special_requests', models.CharField(max_length=100)),
                ('is_completed', models.BooleanField(default=True)),
                ('completed_time', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.user')),
            ],
            options={
                'ordering': ['completed_time'],
            },
        ),
    ]
