# Generated by Django 4.0.8 on 2023-02-14 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_order_is_confirmed_order_shared_people_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='plate_numer',
            new_name='plate_number',
        ),
    ]
